#! /usr/bin/env sh
if [ -z $1 ]
then
		dirpath=$(find -L  ~/Projects ~/testing -mindepth 1 -maxdepth 2 -type d | fzf)
else 
		dirpath=$1
fi

if [ -z $dirpath ]
then
		exit 1
fi

session_name=$(basename "$dirpath" | tr . _)

cd $dirpath
tmux new-session -d -s $session_name -c $dirpath -n "repl"
tmux new-window -n "nvim" -t $session_name
tmux new-window -n "shell" -t $session_name -c $dirpath
tmux send-keys -t "shell" "git status" Enter
tmux send-keys -t "nvim" "nvim" Enter


tmux attach -t $session_name

